import SwiftCompilerPlugin
import SwiftSyntaxMacros

@main
struct KioskMacrosPlugin: CompilerPlugin {
  let providingMacros: [Macro.Type] = [
    InitMacro.self,
    CopyMacro.self,
    MergeMacro.self,
    DataMacro.self,
    LerpMacro.self,
    StyleMacro.self,
    ErasedMacro.self,
    MapMacro.self,
    JsonMacro.self,
    StringMacro.self,
    SnapMacro.self,
    RouteMacro.self,
    ParamMacro.self,
    QueryMacro.self,
    HeaderMacro.self,
    ContentMacro.self,
    WrapMacro.self,
    UnwrapMacro.self,
    PartMacro.self,
    StatusMacro.self,
    SerializableMacro.self,
    FieldMacro.self,
    FormatMacro.self,
    DefaultMacro.self,
    ValidatableMacro.self,
    RequiredMacro.self,
    NonEmptyMacro.self,
    RangeMacro.self,
    PatternMacro.self,
    PastMacro.self,
    FutureMacro.self,
    ValidateMacro.self,
    GetMacro.self,
    PostMacro.self,
    PutMacro.self,
    PatchMacro.self,
    DeleteMacro.self,
    KeyMacro.self,
  ]
}
